import { generateSecret, deriveRak, rak2base64url, base64url2rak, toBase64url, encryptMessage, decryptMessage, genAuthToken } from "../lib/crypto";
import { createRoom, getRoom, joinRoom, getEvents } from "../lib/api";
import type { GetRoomResult, RoomEvent } from "../lib/api";

export interface PlainMember {
  uid: string;
  name: string;
  joinedAt: number; // unix ms
  leftAt?: number; // unix ms; omitted if still in room
}

export interface PlainRoomInfo {
  name: string;
  expiresAt: number;
  memberCount: number;
  maxParticipants: number;
  maxEvents: number;
  members: PlainMember[];
}

export interface CreateRoomServiceResult {
  roomId: string;
  userId: string;
  createdAt: number;
  expiresAt: number;
  joinEid: number;
}

export interface JoinRoomServiceResult {
  userId: string;
  joinEid: number;
  room: PlainRoomInfo;
}

export class RoomService {
  readonly secret: CryptoKey;
  readonly rak: CryptoKey;
  readonly accessKey: string;
  roomId: string | null = null;
  userId: string | null = null;

  private constructor(secret: CryptoKey, rak: CryptoKey, accessKey: string) {
    this.secret = secret;
    this.rak = rak;
    this.accessKey = accessKey;
  }

  static async create(): Promise<RoomService> {
    const secret = await generateSecret();
    const rak = await deriveRak(secret);
    const accessKey = await rak2base64url(rak);
    return new RoomService(secret, rak, accessKey);
  }

  // For joining a room — secret comes from URL hash fragment (already generated by creator)
  static async fromSecret(secret: CryptoKey): Promise<RoomService> {
    const rak = await deriveRak(secret);
    const accessKey = await rak2base64url(rak);
    return new RoomService(secret, rak, accessKey);
  }

  // For rehydrating from localStorage — skips PBKDF2 entirely
  static async restore(data: { secretBytes: string; rakBytes: string; roomId: string; userId: string }): Promise<RoomService> {
    const secret = await RoomService.importSecret(data.secretBytes);
    const rak = await base64url2rak(data.rakBytes);
    const accessKey = data.rakBytes;
    const rs = new RoomService(secret, rak, accessKey);
    rs.roomId = data.roomId;
    rs.userId = data.userId;
    return rs;
  }

  static async exportSecret(secret: CryptoKey): Promise<string> {
    const raw = await crypto.subtle.exportKey("raw", secret);
    return toBase64url(raw);
  }

  static async importSecret(b64url: string): Promise<CryptoKey> {
    const std = b64url.replace(/-/g, "+").replace(/_/g, "/");
    const raw = Uint8Array.from(atob(std), (c) => c.charCodeAt(0));
    return crypto.subtle.importKey("raw", raw, { name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]);
  }

  async makeToken(uid: string | null = null): Promise<string> {
    if (!this.roomId) throw new Error("roomId not set — call createRoom() first");
    return genAuthToken({ rid: this.roomId, uid, ts: Date.now() }, this.rak);
  }

  async createRoom(params: { name: string; creatorName: string }): Promise<CreateRoomServiceResult> {
    const result = await createRoom({
      name: await encryptMessage(params.name, this.secret),
      accessKey: this.accessKey,
      creatorName: await encryptMessage(params.creatorName, this.secret),
    });
    this.roomId = result.roomId;
    this.userId = result.userId;
    return result;
  }

  async getRoom(): Promise<PlainRoomInfo> {
    const token = await this.makeToken(this.userId);
    const raw = await getRoom(this.roomId!, token);
    return this.decryptRoomInfo(raw);
  }

  async joinRoom(params: { name: string }): Promise<JoinRoomServiceResult> {
    const token = await this.makeToken(null);
    const result = await joinRoom({
      roomId: this.roomId!,
      name: await encryptMessage(params.name, this.secret),
      token,
    });
    this.userId = result.userId;
    return {
      userId: result.userId,
      joinEid: result.joinEid,
      room: await this.decryptRoomInfo(result.room),
    };
  }

  async getEvents(afterEid?: number): Promise<RoomEvent[]> {
    const token = await this.makeToken(this.userId);
    return getEvents(this.roomId!, token, afterEid);
  }

  private async decryptRoomInfo(raw: GetRoomResult): Promise<PlainRoomInfo> {
    const [name, ...memberNames] = await Promise.all([
      decryptMessage(raw.name, this.secret),
      ...raw.members.map((m) => decryptMessage(m.name, this.secret)),
    ]);
    return {
      name,
      expiresAt: raw.expiresAt,
      memberCount: raw.memberCount,
      maxParticipants: raw.maxParticipants,
      maxEvents: raw.maxEvents,
      members: raw.members.map((m, i) => ({
        uid: m.uid,
        name: memberNames[i],
        joinedAt: m.joinedAt,
        ...(m.leftAt !== undefined ? { leftAt: m.leftAt } : {}),
      })),
    };
  }
}
