import {
  genAsymmetricKeyPair,
  deriveAES256FromPrivate,
  keyToString,
  stringToPrivateKey,
  encrypt,
  decrypt,
  genAuthToken,
} from "../lib/crypto";
import { createRoom, getRoom, joinRoom, getEvents } from "../lib/api";
import type { GetRoomResult, RoomEvent } from "../lib/api";

export interface PlainMember {
  uid: string;
  name: string;
  joinedAt: number; // unix ms
  leftAt?: number; // unix ms; omitted if still in room
}

export interface PlainRoomInfo {
  name: string;
  expiresAt: number;
  memberCount: number;
  maxParticipants: number;
  maxEvents: number;
  members: PlainMember[];
}

export interface CreateRoomServiceResult {
  roomId: string;
  userId: string;
  createdAt: number;
  expiresAt: number;
  joinEid: number;
}

export interface JoinRoomServiceResult {
  userId: string;
  joinEid: number;
  room: PlainRoomInfo;
}

export class RoomService {
  readonly privateKey: CryptoKey;
  readonly publicKey: CryptoKey;
  readonly aesKey: CryptoKey;
  readonly publicKeyJwk: string;
  roomId: string | null = null;
  userId: string | null = null;

  private constructor(privateKey: CryptoKey, publicKey: CryptoKey, aesKey: CryptoKey, publicKeyJwk: string) {
    this.privateKey = privateKey;
    this.publicKey = publicKey;
    this.aesKey = aesKey;
    this.publicKeyJwk = publicKeyJwk;
  }

  static async create(): Promise<RoomService> {
    const { privateKey, publicKey } = await genAsymmetricKeyPair();
    const aesKey = await deriveAES256FromPrivate(privateKey);
    const publicKeyJwk = await keyToString(publicKey);
    return new RoomService(privateKey, publicKey, aesKey, publicKeyJwk);
  }

  // For joining a room — privateKey comes from URL hash fragment (already generated by creator)
  static async fromPrivateKey(privateKey: CryptoKey): Promise<RoomService> {
    const aesKey = await deriveAES256FromPrivate(privateKey);
    const publicKeyJwk = await keyToString(await RoomService._derivePublicKey(privateKey));
    const publicKey = await RoomService._derivePublicKey(privateKey);
    return new RoomService(privateKey, publicKey, aesKey, publicKeyJwk);
  }

  // For rehydrating from localStorage
  static async restore(data: { privateKeyJwk: string; roomId: string; userId: string }): Promise<RoomService> {
    const privateKey = await stringToPrivateKey(data.privateKeyJwk);
    const aesKey = await deriveAES256FromPrivate(privateKey);
    const publicKey = await RoomService._derivePublicKey(privateKey);
    const publicKeyJwk = await keyToString(publicKey);
    const rs = new RoomService(privateKey, publicKey, aesKey, publicKeyJwk);
    rs.roomId = data.roomId;
    rs.userId = data.userId;
    return rs;
  }

  static async exportPrivateKey(pk: CryptoKey): Promise<string> {
    return keyToString(pk);
  }

  static async importPrivateKey(jwk: string): Promise<CryptoKey> {
    return stringToPrivateKey(jwk);
  }

  // Re-derive the public key from a private key via export/re-import without the "d" field
  private static async _derivePublicKey(privateKey: CryptoKey): Promise<CryptoKey> {
    const jwk = await crypto.subtle.exportKey("jwk", privateKey);
    // Remove private "d" component to get public key JWK
    const { d: _d, ...publicJwk } = jwk;
    void _d;
    return crypto.subtle.importKey(
      "jwk",
      { ...publicJwk, key_ops: ["verify"] },
      { name: "ECDSA", namedCurve: "P-384" },
      true,
      ["verify"],
    );
  }

  async makeToken(uid: string | null = null): Promise<string> {
    if (!this.roomId) throw new Error("roomId not set — call createRoom() first");
    return genAuthToken({ rid: this.roomId, uid, ts: Date.now() }, this.privateKey);
  }

  async createRoom(params: { name: string; creatorName: string }): Promise<CreateRoomServiceResult> {
    const result = await createRoom({
      name: await encrypt(params.name, this.aesKey),
      publicKey: this.publicKeyJwk,
      creatorName: await encrypt(params.creatorName, this.aesKey),
    });
    this.roomId = result.roomId;
    this.userId = result.userId;
    return result;
  }

  async getRoom(): Promise<PlainRoomInfo> {
    const token = await this.makeToken(this.userId);
    const raw = await getRoom(this.roomId!, token);
    return this.decryptRoomInfo(raw);
  }

  async joinRoom(params: { name: string }): Promise<JoinRoomServiceResult> {
    const token = await this.makeToken(null);
    const result = await joinRoom({
      roomId: this.roomId!,
      name: await encrypt(params.name, this.aesKey),
      token,
    });
    this.userId = result.userId;
    return {
      userId: result.userId,
      joinEid: result.joinEid,
      room: await this.decryptRoomInfo(result.room),
    };
  }

  async decryptName(encrypted: string): Promise<string> {
    return decrypt(encrypted, this.aesKey);
  }

  async getEvents(afterEid?: number): Promise<RoomEvent[]> {
    const token = await this.makeToken(this.userId);
    return getEvents(this.roomId!, token, afterEid);
  }

  private async decryptRoomInfo(raw: GetRoomResult): Promise<PlainRoomInfo> {
    const [name, ...memberNames] = await Promise.all([
      decrypt(raw.name, this.aesKey),
      ...raw.members.map((m) => decrypt(m.name, this.aesKey)),
    ]);
    return {
      name,
      expiresAt: raw.expiresAt,
      memberCount: raw.memberCount,
      maxParticipants: raw.maxParticipants,
      maxEvents: raw.maxEvents,
      members: raw.members.map((m, i) => ({
        uid: m.uid,
        name: memberNames[i],
        joinedAt: m.joinedAt,
        ...(m.leftAt !== undefined ? { leftAt: m.leftAt } : {}),
      })),
    };
  }
}
